-- AlterTable
ALTER TABLE "characters" ADD COLUMN     "armorValue" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "currentHp" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "maxHp" INTEGER NOT NULL DEFAULT 100;
